### ISSUE TITLE
trying to run my own as written in the readme

### ISSUE THREAD

**Issue by linojon** [vercel/og-image#204] opened 2022-05-19 19:14 UTC
Helo, i have cloned the project and trying to run it out of the box. I cloned the project, ran yarn install. On Windows 11. Per the "Deploy your own" instructions, i removed all configuration in vercel.json besides rewrites, and run vercel dev, and visit localhost:3000. In the browser i see the "Open Graph Image as a Service" page, and below the heading says "Loading...". The console reports the following error:

```
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "image/png". Strict MIME type checking is enforced for module scripts per HTML spec.
```

**Comment by styfle** [comment] 2022-06-07 03:57
Thanks for reporting! This looks like a duplicate of #180

**Closed by styfle** 2022-06-07 03:57 UTC
