### ISSUE TITLE
Issue when changing default images

### ISSUE THREAD

**Issue by lucatolton** [vercel/og-image#170] opened 2021-09-01 20:03 UTC
Hey! I'm trying to change the default images in the dropdown to match my company, but they just change back when I run "vercel dev".

I'm editing imageLightOptions and imageDarkOptions in public/dist/web/index.js, do I need to edit it anywhere else?

**Comment by styfle** [comment] 2021-09-01 20:50
https://github.com/vercel/og-image/blob/964fca77ed0cca83c879fcba8c67992f1d0fafa8/web/index.ts#L144-L148

https://github.com/vercel/og-image/blob/84e305d4946227ce8383988911f419db57c1cc3e/api/_lib/parser.ts#L53-L65

**Comment by lucatolton** [comment] 2021-09-01 21:02
Sorry, forgot to mention that I've edited both of those files.

**Comment by styfle** [comment] 2021-12-20 17:55
Perhaps you need to clear your browser cache?

**Comment by AmreshSinha** [comment] 2022-01-24 05:39
I am facing the same issue. I did changed both the file and this is what I get :(
![image](https://user-images.githubusercontent.com/35039730/150727937-7a8d7941-97e3-4015-a372-ef7641b6164f.png)

**Comment by styfle** [comment] 2022-01-24 17:11
Does your terminal show an error message?

**Comment by jaredgorski** [comment] 2022-01-24 20:56
The issue when changing the default images is caused by these lines: https://github.com/vercel/og-image/blob/main/api/_lib/parser.ts#L61-L63

```typescript
    if (!images[0].startsWith('https://assets.vercel.com/') && !images[0].startsWith('https://assets.zeit.co/')) {
        images[0] = defaultImage;
    }
```

You'll want to comment that out. Alternatively, Vercel may choose to allow images from other domains.

Then to get the web app to refresh itself, clear your browser cache.

Re. the "Oops, an error occured", if that's not fixed by clearing cache + restarting the server, check to see if you're on an M1 chip Mac. If so, [you may need to use Node v15+](https://stackoverflow.com/questions/65856300/wasm-code-commit-allocation-failed-process-out-of-memory) (CC @styfle regarding this one).

**Comment by jbbelcher53** [comment] 2022-01-26 15:47
@styfle I am getting the same thing, it says: Failed to complete request to (whatever url for the image): Error: connect ECONNREFUSED ::1:53456

**Comment by styfle** [comment] 2022-01-26 17:12
Oh I see now, the error message is from newer versions of chrome not being compatible with an older version of `puppeteer-core`:

```
TimeoutError: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r848005 is guaranteed to work.
    at Timeout.onTimeout (/Users/styfle/Code/vercel/og-image/node_modules/puppeteer-core/src/node/BrowserRunner.ts:238:9)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
```

We'll need to update dependencies.

In the meantime, you can try `OG_HTML_DEBUG=1 vercel dev` and then visit the image directly to see it as HTML, for example:

http://localhost:3000/**Hello**%20World.png?theme=light&md=1&fontSize=100px&images=https%3A%2F%2Fassets.vercel.com%2Fimage%2Fupload%2Ffront%2Fassets%2Fdesign%2Fvercel-triangle-black.svg

**Comment by jbbelcher53** [comment] 2022-01-26 17:54
No changes, and visiting directly doesn't work either, gives a 502 bad gateway NO_RESPONSE_FROM_FUNCTION

**Closed** 2022-01-26 22:50 UTC
Labels: question

**Comment by jbbelcher53** [comment] 2022-02-02 16:16
@styfle this actually appears to be an issue with Node 17 and the Vercel CLI. Downgrading to a lower Node version fixed this issue for me. https://github.com/vercel/vercel/issues/7306

**Comment by styfle** [comment] 2022-02-02 20:15
I believe this is fixed on canary. 

Try “npm i -g vercel@canary”
